name:                space-shooter
version:             0.1.0.0
github:              "siKruger/haskell-spaceshooter"
license:             BSD3
author:              "Simon Krüger& Jeffrey Kahlert"
maintainer:          "sim.krueger@ostfalia.de"
copyright:           "2021 Simon Krüger& Jeffrey Kahlert"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/siKruger/haskell-spaceshooter#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  space-shooter-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - space-shooter
    - gloss
    - random
    - time

tests:
  space-shooter-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - space-shooter
